---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: quay.io/cohesiveio/alpine-build

inputs:
  - name: nginx-src
    path: src
  - name: libressl-build
  # - name: libbrotli-build

outputs:
  - name: nginx-build
  
run:
  path: ./src/build.sh

