---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: quay.io/cohesiveio/alpine-build

run:
  path: src/build.sh
    
inputs:
  - name: src
  - name: libressl
  # - name: libbrotli

outputs:
  - name: out
